language: php

env:
  global:
    - SYMFONY_VERSION=""

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION="3.0.*"
    - php: 7.2
      env: SYMFONY_VERSION="3.0.*"
    - php: 7.1
      env: SYMFONY_VERSION="4.0.*"
    - php: 7.2
      env: SYMFONY_VERSION="4.0.*"
    - php: 7.3
      env: SYMFONY_VERSION="4.4.*"
    - php: 7.3
      env: SYMFONY_VERSION="5.0.*"
    - php: 7.4
      env: SYMFONY_VERSION="5.0.*"
    - php: 7.4
      env: SYMFONY_VERSION="5.1.*"
    # bleeding edge (unreleased dev versions where failures are allowed):
    - php: nightly # PHP 8
      env: SYMFONY_VERSION="5.2.*"
  allow_failures:
    - env: SYMFONY_VERSION="5.2.*"

before_script:
  - composer self-update
  - composer install --prefer-dist

script: ./vendor/bin/phpunit
