language: php

env:
  global:
    - SYMFONY_VERSION=""

matrix:
  include:
    - php: 7.4
      env: SYMFONY_VERSION="5.3.*"
    - php: 8.0
      env: SYMFONY_VERSION="5.3.*"

before_script:
  - composer self-update
  - composer install --prefer-dist

script: ./vendor/bin/simple-phpunit
